name: estranged-ts tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '17.x'
    - name: install libraries
      run: npm install
    - name: run build
      run: npm run build
    - name: run tests
      run: npm run test
    - name: check update
      run: git diff-files -p --exit-code --diff-filter=ADMR -w
